version: "3"

services:
  # client-prod:
  #   container_name: client_prod
  #   build:
  #     context: ./client
  #   ports:
  #     - "3000:80"
  #   depends_on: 
  #     - user_api
  weather_app:
    build:
      context: ./apis/weather
    depends_on:
      - db
    ports:
      - 4243:4243
  user_api:
    build:        
      context: ./server_user
    environment:
      JWT_TOKEN: test
    links:
      - db:database
    depends_on:
      - db
    ports:
      - 4242:4242
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /sessions

volumes:
    db-data:
