version: "3"

services:
  front_service:
    build:
      context: ./client/
    depends_on:
      - user_api
    ports:
      - 80:80
  widgets_api:
    build:
      context: ./apis/
    depends_on:
      - db
    ports:
      - 4244:4244
  user_api:
    build:        
      context: ./server_user
    environment:
      JWT_TOKEN: test
    links:
      - db:database
    depends_on:
      - db
    ports:
      - 8080:4242
    restart: on-failure
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 9000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /sessions
volumes:
    db-data:
