version: "3"

services:
  user_api:
    build:        
      context: ./server_user
    environment:
      ACCESS_TOKEN_SECRET: AZEAZEAZE
      REFRESH_TOKEN_SECRET: AZEAZEAZE
      YOUTUBE_KEY: AIzaSyCBTu2kfemBR9-O4MF-XJaZD4YNj2Ulikc
      WEATHER_KEY: 9478992d291326ad91f980d7b893025f
      CURRENCY_KEY: 990cf10511msh64a893edd2e1083p145fb6jsn72ba086c0b1a
    links:
      - db:database
    depends_on:
      - db
    ports:
      - 8080:4242
    restart: on-failure
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: user_db
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db-data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    depends_on:
      - db
    ports:
      - 9000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - /sessions
volumes:
    db-data:
